name: Build & Deploy

on:
  push: 
    branches: [ feat/ci ]
  workflow_dispatch:

env:
  DOCKER_TAG: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/serverbot
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          workdir: .
          dockerfile: ./Dockerfile
          tags: ${{ env.DOCKER_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deploy
        run: curl --insecure -X POST ${{ secrets.DEPLOY_WEBHOOK }}